Реализовал абстрактный обработчик событий
CorporationX/notification_service pull request #133
Opened 2024-06-12 21:36 UTC by NadirCianid

2024-06-13 13:43 UTC, p1maf requested changes
обсудили в дс по 2 пунктам, к остальному вопросов нет

2024-06-13 13:43 UTC, p1maf commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +        }
у нас в user_serivce где делается запрос на получение пользователя уже есть выброс исключения если его нет

2024-06-13 13:43 UTC, p1maf commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final ObjectMapper objectMapper;
не используешь нигде, но вижу в задание, что он присутствует.
Ты его оставил на потом?

2024-06-13 15:47 UTC, NadirCianid commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final ObjectMapper objectMapper;
Да, оставил на потом. Скорее всего он необходим классам-наследникам

2024-06-15 10:34 UTC, p1maf approved these changes

2024-06-16 17:53 UTC, Sabina-Vishnya approved these changes

2024-06-16 17:53 UTC, Sabina-Vishnya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final ObjectMapper objectMapper;
туду нет, как другой разработчик поймет что на потом и не удалит это? в текущей задаче тебе это нужно? если не требуется-значит не добавляй

2024-06-16 18:28 UTC, merged