Griffon master bc5 bjs2 16453
CorporationX/notification_service pull request #162
Opened 2024-08-13 10:51 UTC by fraifree

2024-08-17 11:50 UTC, fokinms commented on src/main/java/faang/school/notificationservice/config/context/TgNotificationBot.java
> +
висячие строки)

2024-08-17 11:50 UTC, fokinms commented on src/main/java/faang/school/notificationservice/event/FollowerEvent.java
> +public class FollowerEvent {
Здесь скорее всего все-таки LIkeEvent должен быть, судя по заданию?

2024-08-17 11:50 UTC, fokinms commented on src/main/java/faang/school/notificationservice/event/FollowerEvent.java
> +public class FollowerEvent {
ну и по составу Dto в целом

2024-08-17 11:50 UTC, fokinms commented on src/main/java/faang/school/notificationservice/messaging/FollowerMessageBuilder.java
> +public class FollowerMessageBuilder implements MessageBuilder<FollowerEvent> {
Тут тоже, FollowerEvent по идее отдельное событие с другим составом

2024-08-17 11:50 UTC, fokinms commented on src/main/java/faang/school/notificationservice/subscriber/FollowerEventSubscriber.java
> +        implements MessageListener {
тоже нейминг

2024-08-29 09:09 UTC, pablo023 requested changes
По логике окей. Остальное исправь вместе с конфликтами, и можем мержить

2024-08-29 09:09 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/notification_v1.sql
Лучше называть их так, чтобы описывали, что они делают.

2024-08-29 09:09 UTC, pablo023 commented on src/main/resources/application.properties
Это не совсем апп проперти, а конкретно телеграмовские шаблоны. Такое выносится либо в класс с константами, либо вот так, но надо назвать файл более уместно, чтобы понятно было - что он именно к телеграм сообщениям относится.

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/subscriber/RedisAbstractMessageSubscriber.java
> +    protected String getMessage(T event, MessageDto messageDto,
Ну это скорее buildMessage, но не критично

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/subscriber/LikeEventSubscriber.java
> +            sendNotification(author.getId(), getMessage(event, messageDto, Locale.UK));
Почему у тебя тут Locale хардкодится?

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/notification/EmailNotificator.java
Для чего этот класс? Как ты его используешь?

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/notification/SmsNotificator.java
И этот для чего?

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/model/TelegramChat.java
> +@AllArgsConstructor
Тебе не все аннотации нужны. Не говорю какие конкретно - поразбирайся с этим.

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/config/context/TgNotificationBot.java
> +                case "WAITING_FOR_ID":
Для этого используй энам. Разберись с ним. Это немутабельная штука которая по идее не будет меняться на протяжении проекта. Вот это подходит по описанию

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/config/context/TgNotificationBot.java
> +                case "WAITING_FOR_ID":
Я бы эти кейсы повыносил в отдельные методы

2024-08-29 09:09 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/config/context/TelegramBotConfig.java
> +        }
Это не совсем правильная обработка исключений. Нужно предоставлять детали, которые помогут тому, кто будет фиксить ошибку, быстро и легко найти место и причину, почему что-то не так пошло. Просто проброс рантайма тут не поможет, увы

2024-08-29 18:30 UTC, merged