Feature bjs2 25762
CorporationX/notification_service pull request #181
Opened 2024-08-18 18:45 UTC by shade2903

2024-08-20 13:23 UTC, ravshanbekn commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            T event = objectMapper.readValue(message.getBody(), type);
Наверно, тут еще Consumer должен быть

2024-08-20 13:26 UTC, ravshanbekn commented
Хорошо реализовал

2024-08-25 01:50 UTC, pablo023 requested changes

2024-08-25 01:50 UTC, pablo023 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            T event = objectMapper.readValue(message.getBody(), type);
Вов, а что происходит после прочтения сообщения? Этот эвент у нас как-то тут повисает, и по моему ничего не происходит с ним дальше

2024-09-07 13:37 UTC, shade2903 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            T event = objectMapper.readValue(message.getBody(), type);
да здесь забыл Consumer, в индивидуальной задачи написал, здесь забыл.

2024-09-10 02:26 UTC, pablo023 approved these changes

2024-09-10 02:26 UTC, merged