BJS2-26966 Обработчик событий
CorporationX/notification_service pull request #216
Opened 2024-10-07 01:09 UTC by Murzin34

2024-10-08 15:01 UTC, Peregruzochka commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +    protected final ObjectMapper objectMapper;
Для чего здесь нужен этот маппер?

2024-10-08 15:01 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +    path: "user-service"
@mrkorolev, а нужно ли нам это?)

2024-10-08 15:01 UTC, Peregruzochka commented on src/test/java/faang/school/notificationservice/publis/listener/AbstractEventListenerTest.java
> +    private AbstractEventListener<Object> abstractEventListener;
А почему тут не используется `@InjectMock`? А все инициализируется в setUp?

2024-10-08 15:49 UTC, Murzin34 commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +    protected final ObjectMapper objectMapper;
Текст задания: 
Этот класс (AbstractEventListener) содержит в себе следующие бины-зависимости:
ObjectMapper для превращения эвентов из Redis из формата JSON в Java-объекты. 

В общем то нужен для на будущее, для всех лисенеров кто екстендит данный класс. Конкретно для методов getMessage и sendNotification не нужен.

2024-10-08 15:55 UTC, Murzin34 commented on src/main/resources/application.yaml
> +    path: "user-service"
Нужен, пока в UserService есть path)
Иначе `FeignException$NotFound: [404] during [GET] to [http://localhost:8080/users/*userId*]`

2024-10-08 16:04 UTC, Murzin34 commented on src/test/java/faang/school/notificationservice/publis/listener/AbstractEventListenerTest.java
> +    private AbstractEventListener<Object> abstractEventListener;
т.к. AbstractEventListener это абстрактный класс @InjectMocks не робит( ну можно правда заюзать Powermock library чтобы `@InjectMock` всё-таки заработал, или в setUp переопределить весь класс с помощью ReflectionTestUtils. Но самый простой метод вот этот.

2024-10-08 16:13 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +    path: "user-service"
Это был вопрос тому, кто его туда добавил))

2024-10-10 11:42 UTC, 20cognosce requested changes

2024-10-10 11:42 UTC, 20cognosce commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +                .findFirst()
Сделай так, чтобы при множественном совпадении тоже была ошибка
А то ты берешь рандомный первый из 100 условно попавших под условие, это бред

2024-10-10 11:42 UTC, 20cognosce commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +                .findFirst()
Аналогично
.reduce

2024-10-10 15:36 UTC, Murzin34 commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +                .findFirst()
Поправил.

2024-10-10 15:36 UTC, Murzin34 commented on src/main/java/faang/school/notificationservice/publis/listener/AbstractEventListener.java
> +                .findFirst()
Поправил.

2024-10-11 17:10 UTC, 20cognosce approved these changes

2024-10-11 17:10 UTC, merged

2024-10-13 22:52 UTC, mrkorolev commented on src/main/resources/application.yaml
> +    path: "user-service"
@Peregruzochka Казнить, нельзя помиловать))