BJS2-26188 - Created tg bot for sending notifications
CorporationX/notification_service pull request #218
Opened 2024-10-07 19:47 UTC by GusevVrn

И как это тестить

2024-10-08 21:28 UTC, mysosnovskaya requested changes
По тестам - достаточно только юнит тесты на onUpdateReceived метод написать)

2024-10-08 21:28 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> +                    //TODO: Somehow update user in DB to get his correct userId
Поясни, почему chatId не подходит?

2024-10-09 15:46 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> +                    //TODO: Somehow update user in DB to get his correct userId
Ну вообще по хорошему для юзера же сохранить его chatId ( у нас по заданию userId=chatId хотя это же не так))
Запретить пользователю стартовать бота несколько раз, так же сделать отписку.
Тут в этом методе речь идет только про ответные сообщения же. То что ты боту пишешь

По тестам не могу замокать нормально метод execute, ведь тут все сводится к методу sendMessage
```
        when(absSender.execute(SendMessage.builder().chatId(1l).text("l").build()))
                .thenAnswer(answer);
//telegramLongPollingBot.execute
        telegramService.send(userDto, TELEGRAM);

        verify(telegramService.execute(any(SendMessage.class)));
```

пытался сделать что-то такое, он все равно идет вызывать этот метод и падает в ошибку

2024-10-09 20:58 UTC, mysosnovskaya requested changes

2024-10-09 20:58 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/telegram/TelegramBotInitializer.java
> +            throw new RuntimeException(e);
А как мы об этой ошибке узнаем? Кто её залоггирует?

2024-10-09 20:58 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> +                    //TODO: Somehow update user in DB to get his correct userId
А что ты в тесте хочешь проверить? Что execute вызывался? Так не получится, т.к. по сути это метод этого же класса, его не замокать никак

2024-10-10 19:15 UTC, mysosnovskaya approved these changes

2024-10-10 19:15 UTC, merged