start solution BJS2-27521 - Отправка Email сообщений
CorporationX/notification_service pull request #219
Opened 2024-10-07 20:22 UTC by wmwmaks

2024-10-07 23:43 UTC, SharkB38 approved these changes

2024-10-07 23:43 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/controller/EmailController.java
> +        return "Email sent successfully";
Тут бы респонс какой нибудь, а не голую строку возвращать

2024-10-07 23:43 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
Как то мне это не нравится, конкретного предложения нет, но я бы один метод оставил

2024-10-08 07:28 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
Я думаю менять send(UserDto user, String text) в интерфейсе плохая идея. Не везде же используется String subject. А как иначе это сделать не придумал. Перегрузка будто бы классно подошла)

2024-10-08 07:29 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/controller/EmailController.java
> +        return "Email sent successfully";
Меня тоже смущает строка, но хочу ваши мнения услышать, как лучше)

2024-10-08 07:36 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
А если сделать send(UserDto user, EmailDraft draft)? И уже смотреть что там в черновике есть, если нет темы, то кидать дефолтную

2024-10-08 08:00 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
Я думаю, лучше не менять интерфейс, так как этот интерфейс будут реализовать и telegram и sms нотификации,   поэтому в задании указано использовать NotificationService. Для всех наших задач будет один интерфейс и одинаковые методы. Поэтому если subject обязателен, может сделать какой-нибудь дефолтный пока что, или добавить поле String subject с сеттером, который можно менять, но тогда придётся заморочиться с многопоточкой, чтобы при отправке одного сообщения, другое сообщение не изменило это поле) Можем вечером обсудить если что, в ПП)

2024-10-08 08:05 UTC, ArstanSubanov approved these changes
Самый быстрый разработчик на диком западе?😃

2024-10-08 08:05 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/controller/EmailController.java
> +        return "Email sent successfully";
В принципе, я бы даже эндпоинт не делал, только тесты написал и проверил что всё работает. Как я понял, отправка уведомления будет в сервисе, где сначала через redis будет получен UserDto, и затем вызовут метод send()

2024-10-08 08:23 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
Не обратил внимания, что там общий NotificationService, тогда да метод не поменяешь

2024-10-08 09:08 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
А чем вам моя реализация не нравится?) Ничего же не поменялось, он просто вызывается если ему передается третий аргумент и все. Надо обсудить, да

2024-10-08 09:09 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/controller/EmailController.java
> +        return "Email sent successfully";
Да, я тоже думал о том, что он не нужен, но пока оставил, если кто проверить тоже захочет, чтобы не писали сами заново. Удалить-то быстро контроллер этот перед мержем, если Маша скажет ,что он лишний 😃

2024-10-08 09:55 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +    public void send(UserDto user, String text, String subject) {
Посмотрел еще раз, подумал, думаю все таки правильно у тебя сделано

2024-10-08 20:47 UTC, mysosnovskaya requested changes

2024-10-08 20:47 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/controller/EmailController.java
> +        return "Email sent successfully";
Контроллер не нужен, согласна. Очень редко бывает, что на проектах добавляют возможность отправки через http запрос, но это либо какая-то отдельная фича на фронте, либо для тестирования. Но чаще всего емэйл нельзя отправить так просто, только по какому-то событию в системе

2024-10-08 20:47 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        send(user, text, "subject");
С subject нужно что-то решить. Может в конфиг его вынести? Типа "Получено новое уведомление!"

2024-10-08 20:47 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        mailSender.send(message);
Подумаем про обработку ошибок? Что будет, если не удалось отправить?

2024-10-09 01:26 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        }catch (MailException e){
Пробел забыл

2024-10-09 16:10 UTC, ArstanSubanov approved these changes
Молодец) Ещё наверное стоит тесты написать, а то в задании так написано)

2024-10-09 16:10 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/dto/EmailRequestDto.java
> +public class EmailRequestDto {
Этот дто вроде больше не нужен?)

2024-10-09 17:41 UTC, mysosnovskaya requested changes
Не забудь разрешить конфликт)

2024-10-09 17:41 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        send(user, text, "email.subject", Locale.ENGLISH);
А этот subjectCode тогда в константы надо =)

2024-10-09 17:41 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        }catch (MailException e){
Согласна

2024-10-09 17:41 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        try {
А выше исключение не может случиться? Может всё тело обернуть?

2024-10-09 17:41 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        }catch (MailException e){
Я бы вообще Exception ловила)

2024-10-09 17:41 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/dto/EmailRequestDto.java
> +public class EmailRequestDto {
Согласна

2024-10-09 18:45 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/dto/EmailRequestDto.java
> +public class EmailRequestDto {
Точно🙄

2024-10-10 19:35 UTC, mysosnovskaya approved these changes

2024-10-10 19:35 UTC, merged