feature-BJS2-26208: Отправка Email сообщений
CorporationX/notification_service pull request #225
Opened 2024-10-08 18:28 UTC by StepnovaVarvara

2024-10-08 19:32 UTC, Silencemess1ah reviewed
*LGTM*

2024-10-08 19:32 UTC, Silencemess1ah commented on src/test/java/faang/school/notificationservice/service/email/EmailServiceTest.java
> +    }
Тесты огонь! )

2024-10-08 19:32 UTC, Silencemess1ah commented on src/main/resources/application.yaml
> +    password: vyat zzyx phfy xwkg #генерируем для своего Google аккаунта по инструкции https://support.google.com/accounts/answer/185833
не свети почту, а тем более пароль если это реальные... 
![PpDwF8UOhcVABwUrx05TNtYqD_f6rK-q76kon23LiVf7bdS44v0__P86Q8Tsafx8dMMI6Man4OUZqXoPm3EH8Q2k](https://github.com/user-attachments/assets/0965c11b-9c77-4735-a19c-eb91873e7806)

2024-10-08 21:35 UTC, mysosnovskaya requested changes

2024-10-08 21:35 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        emailSender.send(mailMessage);
Подумаем про обработку ошибок? Что будет, если не удалось отправить?

2024-10-08 21:35 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        mailMessage.setText(message);
Там ещё можно subject указать. Может через конфиг его добавить? Например, в конфиге можно будет указать "Получено новое уведомление!" в качестве subject

2024-10-09 02:52 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        mailMessage.setText(message);
Добавила

2024-10-09 02:57 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        emailSender.send(mailMessage);
Добавила

2024-10-09 18:01 UTC, mysosnovskaya requested changes

2024-10-09 18:01 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            throw new RuntimeException("Failed to send email", ex.getCause());
Кто это отловит и залоггирует? GlobalExceptionHandler здесь работать не будет, он только для http запросов

2024-10-09 18:01 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        } catch (MailException ex) {
Можно вообще Exception отловить, на всякий случай)

2024-10-09 18:40 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        } catch (MailException ex) {
Поменяла

2024-10-09 18:50 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            throw new RuntimeException("Failed to send email", ex.getCause());
Такс, этот момент я вообще упустила! Типо вообще не нужно кидать ошибку?

2024-10-09 20:04 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            throw new RuntimeException("Failed to send email", ex.getCause());
Исключение смысла не имеет, если ты на него ничего не завязываешь (например, можно завязать Retryable)

2024-10-09 20:04 UTC, mysosnovskaya approved these changes

2024-10-09 20:04 UTC, merged