BJS2-26197 Отправка SMS сообщений
CorporationX/notification_service pull request #226
Opened 2024-10-08 19:49 UTC by badasscoding

2024-10-08 20:03 UTC, Silencemess1ah reviewed
*LGTM* 
С классом где properties только думаю поправить название чтоб не запутаться
![oqT69jXT4IlJbMgiqoFrQUuFjzuMXvD1XQTb9YVzdR5r3i7vjG9tb31cR2_9pkk-wyHJqDyR](https://github.com/user-attachments/assets/f62df213-f480-49c4-97a9-f99dcbb1441d)

2024-10-08 20:03 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/sms/SmsConfig.java
> +public class SmsConfig {
SmsConfig и SmsConfiguration - слишком уж похоже, может SmsConfigurationProperties / VonageConfigurationProperties это первое что приходит в голову может еще что можно придумать

2024-10-08 21:32 UTC, mysosnovskaya requested changes
Отличная работа)

2024-10-08 21:32 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/sms/SmsConfig.java
> +public class SmsConfig {
С Properties хорошо 👍 С комментарием согласна

2024-10-08 21:32 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/sms/SmsConfig.java
> +@Component
Нужно использовать ConfigurationProperties с заданным префиксом, тогда Value не нужна будет

2024-10-08 21:32 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +        log.info("Sending message: {} to userId = {}", message, user.getId());
Уровень debug лучше

2024-10-08 21:32 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +                log.info("Message sent successfully to {}.", message.getTo());
И здесь debug. Предполагается, что sms будут часто слаться, поэтому не нужно засорять логи  неинформативными сообщениями)

2024-10-09 20:11 UTC, mysosnovskaya approved these changes
Разрешай конфликт и можешь сам мержить и закрывать задачу)

2024-10-10 07:12 UTC, merged