Уведомление о лайке - BJS2-26730
CorporationX/notification_service pull request #227
Opened 2024-10-08 20:49 UTC by fragmatik-top

2024-10-08 21:47 UTC, ostermal7 reviewed
Самый главный момент (помимо пока еще отсутствующих тестов)  - отличия в конфиге. Он должен быть одинаковый и нам надо еще раз договориться по этому поводу. Я думал, что все будут юзать тот, который скинул изначально. И не используй GenericJson.

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +        template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
Это перепиши лучше, GenericJackson может все метаданными сломать. Другой Денис не даст соврать)

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    }
Вообще надо бы один стиль иметь redisTemplate, а то уже у нас они расходятся, это не ок

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    public JedisConnectionFactory jedisConnectionFactory() {
имя бина тоже будет конфликтное

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +        return container;
думаю тут лучше пробел добавить

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    public T handlerEvent(Message message, Class<T> type) {
handleEvent()

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            throw new RuntimeException();
логи ошибки

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +                .orElseThrow(() -> new IllegalArgumentException(""))
текст ошибки

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    public void sendNotification(Long id, String message) {
long userId

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +
лишний пробел

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +@Component
ctrl alt l

2024-10-08 21:47 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/messaging/LikeMessageBuilder.java
> +    private UserServiceClient userServiceClient;
final

2024-10-08 21:47 UTC, ostermal7 commented on src/main/resources/messages_ru.properties
> +like.new = "???????????? {0}, ???????? ???? ?? ??? ???? {1}"
по-моему главная проперти должна заполняться тоже всегда (которая английская)

2024-10-09 06:02 UTC, fragmatik-top commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    }
Если,что просто при конфликте добавишь ты или я твой вариант

2024-10-09 06:06 UTC, fragmatik-top commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            throw new RuntimeException();
Надо сделать globalException

2024-10-09 06:06 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    }
Надо это сразу решить, потому что другие люди будут путаться. Или так каждый будет перетирать редис конфиг, чтобы вставить свою версию) я просто специально скинул коммит, который просто достаточно черипикнуть себе в проект. Локально можешь как хочешь его настраивать, просто в мастер ветку кидать единый стиль

2024-10-09 06:08 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            throw new RuntimeException();
Глобал делается для http запросов, тут он не нужен

2024-10-11 14:22 UTC, ostermal7 reviewed
У тебя у контейнера редиса нет настройуи слушателя. Ты прогонял код по редису? Также у тебя отсутствуют тесты лисенера. Абстрактный класс также плохо настроен. Где логика? Где метод отправки нотификаций, доставания сообщения?

2024-10-11 14:22 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
>      }
А где в конфиге редиса настройка твоего слушателя в контейнере? Ты проверял свой код с редисом?

2024-10-11 14:22 UTC, ostermal7 commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +        String text = getMessage(likeEvent, Locale.getDefault());
У тебя откуда? Нигде не вижу метода getMessage

2024-10-15 13:34 UTC, mikhailov26 requested changes

2024-10-15 13:34 UTC, mikhailov26 commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +        String text = getMessage(likeEvent, Locale.getDefault());
+

2024-10-15 13:34 UTC, mikhailov26 commented on src/main/resources/messages_ru.properties
> +like.new = "???????????? {0}, ???????? ???? ?? ??? ???? {1}"
согласен

2024-10-15 13:34 UTC, mikhailov26 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
Надо обсудить ваши конфиги на дейли

2024-10-17 18:22 UTC, mikhailov26 approved these changes

2024-10-17 18:22 UTC, merged