start solution BJS2-27505-Уведомление о достижении цели (listener)
CorporationX/notification_service pull request #229
Opened 2024-10-08 22:07 UTC by wmwmaks

2024-10-09 03:44 UTC, SharkB38 approved these changes

2024-10-09 03:44 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    private String goalCompletedTopic;
Может параметры отдельно как до этого делали?

2024-10-09 07:36 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    private String goalCompletedTopic;
ну а что звучит неплохо. 
Только порт, хост или топики тоже туда вынести попробуем?

2024-10-09 08:51 UTC, ArstanSubanov approved these changes

2024-10-10 22:14 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/listener/GoalCompletedEventListener.java
> +        log.info("Handle Event: {}", goalCompletedEventDto);
Забыл убрать. Исправить на debug нормально будет?

2024-10-12 14:05 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    private String goalCompletedTopic;
Вроде никто не выносит ахах, так что пусть так будет?

2024-10-12 14:08 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    private String goalCompletedTopic;
Видимо, да. Оставляем так 😃

2024-10-12 14:09 UTC, SharkB38 approved these changes

2024-10-12 17:59 UTC, mysosnovskaya requested changes

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    public ChannelTopic goalCompletedTopic() {
Модификатор здесь есть, а выше нигде нет) Почему?

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
Почему бы здесь не сделать `RedisTemplate<String, String>`, если ты точно знаешь, что возвращается строка? В целом в хелпе обсуждался вопрос про разные бины для разных значений, можно и такое сделать. У каждого из подходов есть свои плюсы и минусы: если делать разные бины, то это больше бинов, а если делать один бин, то это в каждом прописывать строчку с objectMapper. 
Я не думаю, что это критично. На реальных проектах можно встретить и то, и другое. Но я бы всё равно рекомендовала сделать разные бины, т.к. так основной рабочий код (имею в виду listener) будет чище, и ошибка так будет отловлена ещё раньше. Готова обсудить это дополнительно, если нужно)

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +Когда Арстан свой таск закроет, возьму его реализацию
Ок

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final List<NotificationService> services;
Здесь лучше сделать `Map<PreferredContact, NotificationService>`, тогда в методе sendNotification поиск будет происходить быстрее, а строчек кода станет меньше)

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/GoalCompletedEventListener.java
> +            , List<NotificationService> services, MessageBuilder<GoalCompletedEventDto> messageBuilder) {
Запятая не там)
А кстати, где наш чекстайл? Почему он это не отловил интересно?
PS: посмотрела, он отловил, но записал это в warn, сборку фейлить не стал. А должен был. Максим, поправь это, пожалуйста. При любых ошибках стиля сборка не должна проходить

2024-10-12 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/GoalCompletedEventListener.java
> +public class GoalCompletedEventListener extends AbstractEventListener<GoalCompletedEventDto> implements MessageListener {
Почему "implements MessageListener" здесь, а не в абстрактном классе? Как другие наследники класса AbstractEventListener узнают, что нужно реализовать метод onMessage, чтобы всё заработало?

2024-10-12 21:47 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/listener/GoalCompletedEventListener.java
> +            , List<NotificationService> services, MessageBuilder<GoalCompletedEventDto> messageBuilder) {
Сделать отдельный таск под это или могу тут исправить?

2024-10-12 21:49 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
Я попытался переделать под <String,String>. Правильно понял, что сделать надо?

2024-10-16 13:32 UTC, mysosnovskaya reviewed
Всё ок, ждем Арстана. А тесты не получится на это дело написать?)

2024-10-17 19:07 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/dto/event/GoalCompletedEventDto.java
> +        long eventId,
Тут видимо тоже goalId?

2024-10-20 11:20 UTC, merged