Отправка сообщений в Telegram
CorporationX/notification_service pull request #231
Opened 2024-10-09 08:26 UTC by Alginin

2. Создан бот.
3. Создана вся необходимая конфигурация для коммуникации в application.yaml.
4. TelegramService реализует интерфейс NotificationService.
5. Написаны unit-тесты.

2024-10-09 14:05 UTC, Peregruzochka reviewed
вери гуд

2024-10-09 14:05 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +  telegram-bot:
вынеси эту инфу в отдельный yaml
посмотри, как добавлять новый yaml к application.yaml

2024-10-09 14:05 UTC, Peregruzochka commented on src/main/java/faang/school/notificationservice/config/telegram/BotConfig.java
> +public class BotConfig {
Лучше чтобы этот класс создавал `bean TelegramBot` и принимал в себя параметры name и токен
Соответственно у TelegramBot убрать аннотацию @Component

2024-10-09 14:05 UTC, Peregruzochka commented on src/main/java/faang/school/notificationservice/telegram/TelegramBot.java
> +
Прикол в том, что тыв не можешь отправить сообщение пользователю не зная его telegramId (чтобы его узнать, необходимо, чтобы пользователь как минимум зашел в бота) таким образом стоит подумать как собирать и где хранить эти telegramId

Но возможно это задача другого микросервиса/сервиса, и тебе не надо сейчас париться на этот счет

2024-10-09 14:05 UTC, Peregruzochka commented on src/main/java/faang/school/notificationservice/service/TelegramBotService.java
> +        }
Валидацию можно в отдельный приватный метод
log.error в данном случае а не log.info

2024-10-13 17:50 UTC, mrkorolev reviewed
Мне нравится )

2024-10-13 17:50 UTC, mrkorolev commented on src/main/java/faang/school/notificationservice/service/TelegramBotService.java
> +        validation(user, message);
Нейминг - можно и получше придумать

2024-10-15 20:58 UTC, 20cognosce requested changes

2024-10-15 20:58 UTC, 20cognosce commented on src/main/resources/telegram-bot.yaml
> +telegram-bot:
Что это за yaml
сделай конфигурационный файл application-telegram.yaml и включи его в основной
через include

Его название просто не сочетается ни с чем

2024-10-15 20:58 UTC, 20cognosce commented on .gitignore
> +telegram-bot.yaml
Может тогда это в env вынести, если ты не хочешь его версионировать
Почему он тогда попал на ПР, интересно

Определись уж, добавлять его в гит или нет

2024-10-15 20:58 UTC, 20cognosce commented on src/main/java/faang/school/notificationservice/telegram/TelegramBot.java
> +    public void onUpdateReceived(Update update) {
Почему пустой метод, что он делает?

2024-10-15 20:58 UTC, 20cognosce commented on src/main/java/faang/school/notificationservice/service/TelegramBotService.java
> +            telegramBot.execute(sendMessage);
А кому это сообщение ушло? Боту?
Сделай sequence диаграмму и проведи демо работы твоей фичи, подготовь к дейли пожалуйста

2024-10-22 19:33 UTC, 20cognosce approved these changes

2024-10-22 19:33 UTC, merged