Таска пока без тестов
CorporationX/notification_service pull request #237
Opened 2024-10-09 19:48 UTC by alibaysarov

2024-10-09 20:26 UTC, ostermal7 reviewed
Вроде ок, главное потом тестами покрыть не забыть)

2024-10-11 15:12 UTC, ostermal7 commented
В мастер ветке сейчас появился сервис, так что надо прогнать будет и тесты перенастроить

2024-10-17 18:33 UTC, mikhailov26 requested changes
Иерархия

2024-10-17 18:34 UTC, mikhailov26 commented
Падает билд, разберись с этим. Ну и конфликты

2024-10-20 11:24 UTC, closed without merging

2024-10-20 11:24 UTC, alibaysarov commented
123