BJS2-27522: Обработчик событий
CorporationX/notification_service pull request #242
Opened 2024-10-11 16:37 UTC by ArstanSubanov

Я оказывается взял задачу не посмотрев все лекции, там Влад уже разбирал эту задачу и я сколько думал, не смог не усложняя улучшить этот класс(

2024-10-11 19:40 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/client/FeignConfig.java
> +    public Retryer feignRetryer() {
Как это работает? Запросы к сервису нотификаций будут идти повторно при неудаче или наоборот сервис нотификаций будет пытаться с другими связаться несколько раз?

2024-10-11 19:42 UTC, wmwmaks approved these changes
👍

2024-10-12 08:14 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    protected void sendNotification(Long id, String message) {
Сейчас делаю задачу, где нужно уведомить всех участников ивента о его старте. Может, повесить на этот метод @Async? Чтобы уведомления рассылались быстрее, если участников будет много?

2024-10-12 16:51 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/client/FeignConfig.java
> +    public Retryer feignRetryer() {
Сервис нотификации должен по несколько раз стучаться в другие сервисы, если я не ошибся с настройкой

2024-10-12 16:52 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    protected void sendNotification(Long id, String message) {
Да, отличная идея, спасибо, добавлю асинхронность)

2024-10-12 19:09 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final List<NotificationService> notificationServices;
мне Маша такой комментарий дала на эту строку)
https://github.com/CorporationX/notification_service/pull/229#discussion_r1797740498

2024-10-13 08:06 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    private final List<NotificationService> notificationServices;
Да, изменил класс по этому комментарию, спасибо)

2024-10-15 17:38 UTC, mysosnovskaya requested changes

2024-10-15 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/client/FeignConfig.java
> +        return new Retryer.Default(100, SECONDS.toMillis(5), 3);
Вот все эти числа в идеале нужно вынести в конфиг

2024-10-15 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/TaskExecutorConfig.java
> +@EnableAsync
Обсуждали в другом ПРе, чаще все эта аннотация выносится в главный класс приложения

2024-10-15 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            log.error(String.valueOf(e));
Это что-то странное =) А вообще - нам точно нужно логгировать это исключение отдельно? Спринг сам не залоггирует вместе со стектрейсом? Проверь, пожалуйста

2024-10-16 14:29 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            log.error(String.valueOf(e));
Проверил, вручную нужно логгировать)

2024-10-16 19:10 UTC, mysosnovskaya approved these changes

2024-10-16 19:10 UTC, merged