BJS2-26203 - Created published for new comment event
CorporationX/notification_service pull request #247
Opened 2024-10-11 21:24 UTC by GusevVrn

2024-10-15 06:22 UTC, Silencemess1ah reviewed
Looks good to me

2024-10-15 06:22 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +}
У тебя ж вроде был уже и даже мерджился или я путаю? Огонь! Там да ж отдельная таска на это есть)

2024-10-15 18:20 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +}
Путаешь, там другая ветка на ревью еще)

2024-10-17 18:58 UTC, mysosnovskaya requested changes

2024-10-17 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            log.info("handleEvent() - start");
Про логи уже говорили в другом ПР, здесь аналогично

2024-10-17 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/NewCommentEventListener.java
> +            log.info("Got post's author - {}", userToNotify);
Слишком много логов

2024-10-17 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/messaging/NewCommentEventBuilder.java
> +    private static final int FINISH_MESSAGE_INDEX = 20;
Почему 20? Лучше вынести в application.yaml, чтобы иметь возможность настраивать этот параметр

2024-10-18 19:05 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            log.info("handleEvent() - start");
щас вроде норм, только старт и стоп, все остальное в дебаг

2024-10-19 14:19 UTC, mysosnovskaya requested changes

2024-10-19 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +                Pair.of(likePostMessageListener, likePostTopic),
Посмотри, пожалуйста, ПР Вари в сервисе нотификаций про лайки. Я писала про этот код комментарий. Это может кто-то один из вас сделать, а второй подтянуть, можете обсудить

2024-10-20 19:46 UTC, mysosnovskaya requested changes

2024-10-20 19:46 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public RedisMessageListenerContainer redisContainer(MessageListenerAdapter goalCompletedMessageListener,
Решение с Pair мне как раз нравилось. Я предлагала создать бины для каждого Pair, а здесь всё оставить как было. Т.е. вместо создания бина для `List<Pair<MessageListenerAdapter, ChannelTopic>>`, создать много бинов для `Pair<MessageListenerAdapter, ChannelTopic>`. А дальше спринг сам соберет это всё в лист (например, как делает с `List<NotificationService>`). Готова обсудить голосом, если нужно)

2024-10-20 20:00 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public RedisMessageListenerContainer redisContainer(MessageListenerAdapter goalCompletedMessageListener,
Ок, но я все равно чет не але с этими pair, намного больше телодвижений чтоб просто не писать addListener.

2024-10-21 18:32 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public RedisMessageListenerContainer redisContainer(MessageListenerAdapter goalCompletedMessageListener,
У нас просто на проекте нет чекстайла =) Есть ограничение по количеству параметров в методе

2024-10-21 18:33 UTC, mysosnovskaya approved these changes

2024-10-21 21:34 UTC, merged