Feature bjs2 27506
CorporationX/notification_service pull request #256
Opened 2024-10-12 17:33 UTC by wmwmaks

2024-10-13 06:21 UTC, SharkB38 approved these changes

2024-10-13 06:21 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/messaging/EventStartEventMessageBuilder.java
> +    }
Хмм, eventServiceClient только для того чтобы получать название события?

2024-10-13 10:51 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/messaging/EventStartEventMessageBuilder.java
> +    }
Сейчас, да. Что тебя смущает?)

2024-10-13 12:24 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/messaging/EventStartEventMessageBuilder.java
> +    }
Ну честно, я бы через реддис передал

2024-10-13 12:54 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/messaging/EventStartEventMessageBuilder.java
> +    }
А вообще я же в dto и так title передаю...Тогда да, можно убрать это обращение к сервису. Переделаю

2024-10-13 16:34 UTC, ArstanSubanov approved these changes
👍

2024-10-13 16:34 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/client/EventServiceClient.java
> +    EventDto getEvent(@PathVariable long eventId);
На самом деле, если хочешь стучаться в user_service, ты мог этот метод добавить в UserServiceClient, не создавая отдельный клиент)

2024-10-13 16:34 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
RedisTemplate вроде не используется?)

2024-10-13 20:23 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/client/EventServiceClient.java
> +    EventDto getEvent(@PathVariable long eventId);
Вот это я не очень понял, видимо. Мы делаем ...ServiceClient - как сервис микросервис или как сервис (который из тройки сервис-контроллер-репозиторий). 
То есть все методы, которые получаем из user_service, можем в UserServiceClient просто добавлять?

2024-10-14 02:57 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/client/EventServiceClient.java
> +    EventDto getEvent(@PathVariable long eventId);
Да, UserServiceClient настроен на вызовы эндпоинтов из микросервиса user_service, поэтому ты можешь добавить туда вызов эндпоинта и всё должно работать)

2024-10-14 05:58 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/client/EventServiceClient.java
> +    EventDto getEvent(@PathVariable long eventId);
Хорошо, я понял. Исправлю тогда. Спасибо)

2024-10-15 17:20 UTC, RuslanIovlev commented
все круто, осталось только под общий стандарт сделать 👌🏻

2024-10-15 17:20 UTC, RuslanIovlev approved these changes

2024-10-16 13:27 UTC, mysosnovskaya requested changes

2024-10-16 13:27 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/EventStartEventListener.java
> +            , List<NotificationService> services, MessageBuilder<EventDto> messageBuilder) {
Стиииль) Подтяни из мастера проверку и поправь всё

2024-10-16 19:16 UTC, mysosnovskaya requested changes

2024-10-16 19:16 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/dto/event/EventDto.java
> +        List<Long> usersId,
userIds (обычно s пишут в конце, так удобнее понимать, что это коллекция. Когда s в середине, то это можно и не заметить)

2024-10-16 19:16 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/messaging/MessageBuilder.java
> -    Class<?> getInstance();
Почему стал не нужен?

2024-10-16 19:16 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +Когда Арстан свой таск закроет, возьму его реализацию
Закрыл)

2024-10-17 12:25 UTC, wmwmaks commented on src/main/java/faang/school/notificationservice/messaging/MessageBuilder.java
> -    Class<?> getInstance();
В моей реализации не использовался. В дискорде у Влада спрашивали про этот метод. Он сказал, если не используете, можете удалять. У Арстана он используется, верну.

2024-10-17 13:35 UTC, aassylkhan approved these changes

2024-10-17 19:12 UTC, mysosnovskaya requested changes

2024-10-17 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/EventStartEventListener.java
> +public class EventStartEventListener extends AbstractEventListener<EventDto> implements MessageListener {
У нас абстрактный класс уже имплементирует этот интерфейс, поэтому здесь это не нужно
https://github.com/CorporationX/notification_service/blob/hydra-master-stream6/src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java#L23

2024-10-20 19:54 UTC, merged