BJS2-26210 Уведомление о подписке
CorporationX/notification_service pull request #265
Opened 2024-10-13 14:53 UTC by badasscoding

2024-10-15 06:53 UTC, Silencemess1ah reviewed
Гуть

2024-10-15 06:53 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    }
Прикольно конечно как идея, но по мне не слишком читабельно будет в будущем, да и не думаю что оно нужно здесь, но за задумку лайк

2024-10-15 06:53 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/service/user/UserService.java
> +}
Отсюда пришел из onMessage метода, у нас же есть UserServiceClient с методом getUser , не понял пока зачем это

2024-10-15 10:02 UTC, imerku1ov commented on src/main/java/faang/school/notificationservice/service/user/UserService.java
> +}
Это скорей фасад https://refactoring.guru/ru/design-patterns/facade над внешним сервисом
В дальнейшем может будет кэш какой-то или другие операции с юзером, хочется чтобы они выполнялись из одного места

2024-10-15 18:08 UTC, mysosnovskaya requested changes

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +        RedisStandaloneConfiguration redisConfig = new RedisStandaloneConfiguration(
Кстати, это можно не делать, спринг умеет сам брать хост и порт для редиса, если они лежат по правильному пути в application.yaml (spring.data.redis - как раз как у нас)

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    }
Это ты про forEach? А это вообще вряд ли кто-то читать будет =) Это один раз пишется и почти никогда не меняется. Так что от меня лайк за идею 👍 Я бы только чуть оформила по-другому, более явно:
```
 requesters.forEach(
      (requester) -> container.addMessageListener(requester.getFirst(), requester.getSecond())
 );
```

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/follower/RedisFollowerTopicConfig.java
> +    @Bean
А тебе где-то этот followerTopic как бин нужен? Сейчас ты им пользуешься просто как методом. Может быть тогда в followerRequester передать ещё и ChannelTopic сразу нужный?

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/follower/RedisFollowerTopicConfig.java
> +    public Pair<MessageListenerAdapter, ChannelTopic> followerRequester(MessageListenerAdapter followerMessageListener) {
Я бы назвала followerListenerChannelPait

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractMessageListener.java
> +    protected void handleEvent(Class<T> klass, Message message, Consumer<T> callback) {
Чаще пишут clazz

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractMessageListener.java
> +            throw new RuntimeException("Failed to deserialize event of type: " + klass.getSimpleName(), e);
А спринг точно сам не залогирует это исключение? Проверь, пожалуйста. А то может получиться дублирование стектрейса в логах

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/follower/FollowerMessageListener.java
> +                notificationServices.stream()
Чтобы не делать этот стрим, сделай поле `Map<PreferredContact, NotificationService>`, тогда можно сразу по ключу доставать нужный сервис

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/follower/FollowerMessageListener.java
> +                                () -> log.warn("No matching notification service found for user preference: {}",
Это не ворнинг, это ЭРРОР =)

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/follower/FollowerMessageListener.java
> +            try {
Я бы эту лямбду вынесла в отдельный приватный метод

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/follower/FollowerMessageListener.java
> +                notificationServices.stream()
А эта логика разве не будет одинаковой для всех наследников абстрактного класса? Подумай, нельзя ли ещё как-то обобщить

2024-10-15 18:08 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/user/UserService.java
> +}
Да, пока выглядит неоправданно, т.к. мы не понимаем, понадобится ли нам ещё какая-то логика сверху или нет. Но пусть будет, в целом этот класс не особо нам мешает

2024-10-18 15:48 UTC, mysosnovskaya commented
Пофикси конфликты и будем мержить)

2024-10-18 18:24 UTC, merged