Уведомление о лайке
CorporationX/notification_service pull request #266
Opened 2024-10-13 15:13 UTC by RuslanIovlev

2024-10-14 03:24 UTC, ArstanSubanov approved these changes
👍

2024-10-14 13:39 UTC, SharkB38 approved these changes

2024-10-15 17:42 UTC, mysosnovskaya requested changes

2024-10-15 17:42 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +            throw new IllegalArgumentException("No notification service found " +
В ошибку нужно добавить, для какого user.getPreference() не нашлось подходящего метода

2024-10-15 17:42 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +            String text = getMessage(likeEvent, Locale.UK);
Всю эту лямбду лучше вынести в отдельный приватный метод

2024-10-15 17:42 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +                log.info("Notification sent successfully to author ID: {}", likeEvent.postAuthorId());
Тут тоже debug уровень лучше подойдет. Представь, если бы в ютубе на каждый лайк делалась бы запись в лог, у них сразу гигабайтные логи были бы, среди которых ничего кроме однотипного сообщения было бы невозможно найти)

2024-10-15 19:25 UTC, RuslanIovlev commented on src/main/java/faang/school/notificationservice/listener/LikeEventListener.java
> +                log.info("Notification sent successfully to author ID: {}", likeEvent.postAuthorId());
Согласен, исправлю

2024-10-16 13:29 UTC, mysosnovskaya requested changes
Поправь конфликт) И как будто бы тестов не хватает

2024-10-19 14:45 UTC, mysosnovskaya approved these changes

2024-10-19 14:45 UTC, merged