feature-BJS2-26212: Уведомление о получении достижения
CorporationX/notification_service pull request #278
Opened 2024-10-15 20:16 UTC by StepnovaVarvara

2024-10-15 20:20 UTC, GusevVrn reviewed
В целом хорошо, 
Маша тебе предложит переделать листы в абстрактном классе чтоб не пробегаться по листам каждый раз)

2024-10-15 20:20 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/service/NotificationService.java
> +
вот этого можно и не делать)

2024-10-15 20:20 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/service/listener/AbstractEventListener.java
> +
лишний отступ

2024-10-15 20:29 UTC, StepnovaVarvara commented
> В целом хорошо, Маша тебе предложит переделать листы в абстрактном классе чтоб не пробегаться по листам каждый раз)

Я попробовала так сделать и пришла к выводу, что это сильно усложнит нам жизнь! Как я поняла, смысл этого действия - быстрее по ключу находить значения. И для этого нам надо сделать отдельный класс с двумя мапами, которые там необходимо инициализировать, чтобы они не были пустыми. А при инициализации тянуться зависимости других классов и тд. Это сложно и много кода + при появлении новых лиснеров и билдеров эти мапы нужно менять. А с листами ничего этого делать не нужно, все само прекрасно работает) + разницу во времени у листа и мапы мы даже не заметим, тк там вряд ли у нас когда-нибудь будет больше 10-20 сервисов для отправки уведомлений)

2024-10-16 19:49 UTC, StepnovaVarvara commented
> > В целом хорошо, Маша тебе предложит переделать листы в абстрактном классе чтоб не пробегаться по листам каждый раз)
> 
> Я попробовала так сделать и пришла к выводу, что это сильно усложнит нам жизнь! Как я поняла, смысл этого действия - быстрее по ключу находить значения. И для этого нам надо сделать отдельный класс с двумя мапами, которые там необходимо инициализировать, чтобы они не были пустыми. А при инициализации тянуться зависимости других классов и тд. Это сложно и много кода + при появлении новых лиснеров и билдеров эти мапы нужно менять. А с листами ничего этого делать не нужно, все само прекрасно работает) + разницу во времени у листа и мапы мы даже не заметим, тк там вряд ли у нас когда-нибудь будет больше 10-20 сервисов для отправки уведомлений)

Короче, я тупица, тк всю эту инициализацию делала ручками!! После того как сделала как надо, то все равно остался вопрос - на сколько это оправдано в данном случае? Но я оч довольна, что так сделала)

2024-10-17 16:48 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/service/listener/AbstractEventListener.java
> +
убрала

2024-10-18 18:33 UTC, mysosnovskaya approved these changes
Поправь конфликты и будем мержить) Ты молодец!)

2024-10-19 14:16 UTC, mysosnovskaya requested changes

2024-10-19 14:16 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/message/MessageSourceConfig.java
> -public class MessageSourceConfig {
Почему этот класс удален?

2024-10-19 14:16 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public List<Pair<MessageListenerAdapter, ChannelTopic>> requesters(
Что-то мне не нравится эта стена кода. Оно уже выглядит не очень, а когда топиков станет больше, то будет совсем некрасиво. Что предлагаю: вместо того, чтобы на каждый топик создавать два бина (MessageListenerAdapter и ChannelTopic), создать один бин - Pair.of(messageListenerAdapter, channelTopic). А в redisContainer спринг подставит самостоятельно, т.е. отдельно создавать бин` List<Pair<MessageListenerAdapter, ChannelTopic>>` будет не нужно. Так и будущим разработчикам будет легче добавлять новый топик в конфиг. Что думаешь?

2024-10-19 14:45 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/config/message/MessageSourceConfig.java
> -public class MessageSourceConfig {
Этот класс я удалила, тк у нас уже есть такой, только с другим названием, просто Message называется. С чьим-то мерджем залетел

2024-10-19 20:41 UTC, GusevVrn commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public List<Pair<MessageListenerAdapter, ChannelTopic>> requesters(
@mysosnovskaya сперва ты утвердила такую конфигурацию, теперь все возвращаем :D
Я когда первый раз увидел подумал в целом прикольная штука... пока сам не столкнулся с конфигурацией. Получается что так даже больше кода и я там в 2х соснах умудрился запутаться)

@StepnovaVarvara там вроде к моему коду больше претензий нету, я залил. Можешь подождать, можешь посмотреть как сделано (26203) и себе скопировать. По поводу MessageSourceConfig я в своем PR оставил как раз твой конфиг и удалил другой))

2024-10-22 18:34 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public List<Pair<MessageListenerAdapter, ChannelTopic>> requesters(
На самом деле щас тоже стена жесткая, мне оч сложно в ней ориентироваться))

2024-10-22 18:36 UTC, StepnovaVarvara commented on src/main/java/faang/school/notificationservice/config/message/MessageSourceConfig.java
> -public class MessageSourceConfig {
Щас вернула его обратно, а другой удалила))

2024-10-22 19:13 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfiguration.java
> +    public List<Pair<MessageListenerAdapter, ChannelTopic>> requesters(
> сперва ты утвердила такую конфигурацию, теперь все возвращаем

меняется проект, меняются решения) Мы никогда не знаем, как будет дальше, и принимаем решения исходя из текущей ситуации. Сначала было нормально так, а теперь топиков стало всё больше и нужно придумать что-то более красивое) Это жизнь!)

2024-10-22 19:15 UTC, mysosnovskaya approved these changes

2024-10-22 19:27 UTC, merged