Feature bjs2 27527
CorporationX/notification_service pull request #284
Opened 2024-10-16 12:50 UTC by KarabbasBarabas

2024-10-16 16:41 UTC, soulasphyxia commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
немного не понял суть абстрактного класса в данном случае. только чтобы в наследнике каждый раз не инжектить final поля? мне кажется, что реализация конкретного листенера меняется только в передаваемом DTO. тогда предложу использовать абстрактный класс, как место, в котором можно описать логику, которая будет общая для всех листенеров: найти предпочитаемый контакт, создать сообщение и отправить его. если у тебя возникнут затруднения, можешь обратиться к лекции Влада на платформе по вынесению логики в абстрактный класс, там как раз на примере notification_service, на самом деле это очень круто как мне кажется)

2024-10-16 16:42 UTC, soulasphyxia commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    final ObjectMapper objectMapper;
мне кажется, ты забыл указать модификатор доступа

2024-10-16 18:47 UTC, RuslanIovlev commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Согласен, можешь глянуть мой пр, там есть примерная реализация

2024-10-16 18:54 UTC, RuslanIovlev commented on src/main/resources/messages.properties
> +follower.new = Congrats! You have got a new follower with id {0}!
Я бы посоветовал в билдере вызвать userServiceClient и получить имя полбзователяб вместо айдишника, для восприятия реального пользователя как будто бы лучше, но это так предложение)

2024-10-16 19:00 UTC, RuslanIovlev commented
в целом все круто, только посмотри что писал Валера у нас в чате про общий стандарт)

2024-10-17 03:56 UTC, ArstanSubanov reviewed
Думаю, тебе стоит почитать Правила для redis config от Валеры, в нашем чате в дискорде, мы осуждали конфиг на последнем ретро)

2024-10-17 03:56 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Я сделал AbstractEventListener и его уже смержили, можешь его использовать)

2024-10-17 03:56 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    final ObjectMapper objectMapper;
Думаю, он оставил модификатор как default наверное)

2024-10-17 08:32 UTC, soulasphyxia commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    final ObjectMapper objectMapper;
не безопаснее ли для абстрактного класса использовать protected?

2024-10-17 10:26 UTC, SharkB38 requested changes

2024-10-17 10:26 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +public class RedisConfig {
Поправь пожалуйста конфиг в соответствии с общими правилами
https://discord.com/channels/1102662981743030334/1267555771944796171/1295396116313149516

2024-10-17 17:29 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    final ObjectMapper objectMapper;
По идее default более безопаснее с точки зрения доступа, так как область видимости ограничен пакетом. Конкретно в этом случае, я не совсем уверен, но я сделал protected, так как мы не договаривались как структурировать наши пакеты, и могло получится так, что кто-то захочет наследоваться из другого пакета)

2024-10-17 19:17 UTC, mysosnovskaya commented
1. Комментарии с кросс-ревью не обработаны - значит ко мне на ревью ещё отправлять рано)
2. Не прошла сборка - надо пофиксить
3. И возникли конфликты - тоже надо их пофиксить)

2024-10-17 19:58 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
да, про более конкретную реализацию согласен

2024-10-17 20:00 UTC, KarabbasBarabas commented on src/main/resources/messages.properties
> +follower.new = Congrats! You have got a new follower with id {0}!
да, согласен, не стал заморачиваться. Ещё можно добавить имя пользователя в событие

2024-10-17 20:05 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
посмотрел, круто.
Подскажи, зачем Async на sendNotification?

2024-10-18 05:44 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Это Максим предложил, я подумал что это хорошая идея) Чтобы отправка сообщений происходила асинхронно, так как может быть много нотификаций происходить и чтобы main поток не ждал, пока отправится сообщение. Например, у тебя же вроде нужно юзеру chatId присвоить? Может быть ещё и в user_service сходить и сохранить у юзера этот chatId. Это может занять определенное время, а за это время поток мог уже отправить парочку email или смс нотификаций)

2024-10-18 07:15 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Да, понимаю, что чтобы асинхронно, слышал, что спринг вроде сам асинхронные запросы делает или это только для контроллера?

2024-10-18 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Вряд ли у брокера сообщений на каждый message будет создаваться отдельный поток, представь там юзер совершает кучу действий(лайкает, комментит, постит и т.д.), по всем этим действиям если будет создаваться отдельный поток, то это на каждого пользователя может создаваться ещё по несколько потоков, у нас ресурсов сервера просто не хватит) Можно это легко проверить, попробуй отправить ивент и где получаешь его в методе onMessage вывести имя текущего потока, я сам не могу посмотреть, так как ещё на работе)

2024-10-18 07:38 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +public class RedisConfig {
поправил

2024-10-18 10:11 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
понял, спасибо

2024-10-18 10:14 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
а ты когда @EnableAutoConfiguration убрал у класса приложения это ты для чего то сделал?

2024-10-18 11:13 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
По-моему у меня там компилятор ругался на него, поэтому убрал так как вроде бы @SpringBootApplication уже содержит эту аннотацию)

2024-10-18 15:28 UTC, mysosnovskaya requested changes

2024-10-18 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> -        Update update = getUpdateForTelegramBot(user.getUsername(), message);
Написала в другом ПРе, напишу и в этом: это выглядит как фикс, напрямую не относящийся к твоей задаче. Это так?

2024-10-18 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/listener/FollowerEventListener.java
> +    private static final Locale DEFAULT_LOCALE = Locale.ENGLISH;
Может это в конфиг вынести? Тогда можно будет запустить несколько экземпляров сервиса с разными локалями)

2024-10-21 14:53 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/FollowerEventListener.java
> +    private static final Locale DEFAULT_LOCALE = Locale.ENGLISH;
может так пускай пока останется

2024-10-21 14:54 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> -        Update update = getUpdateForTelegramBot(user.getUsername(), message);
нет
это получение объекта Update, который используется для отправки сообщения через телеграмм

2024-10-21 14:54 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
нет

2024-10-21 15:19 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Кстати да @SpringBootApplication ее содержит, но почему то без отдельного @EnableAutoConfiguration не запускался сервис, так что надо оставить

2024-10-21 15:47 UTC, ArstanSubanov commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Redundant declaration: @SpringBootApplication already applies @EnableAutoConfiguration. У меня так ругается компилятор, поэтому я её тогда убрал. Я разобрался почему не работает без @EnableAutoConfiguration, так как там указано @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}), то есть эта строка убирает автоконфигурацию компонентов связанных с базой данных, в том числе и репозитории. Поэтому я бы всё таки убрал (exclude = {DataSourceAutoConfiguration.class}) и @EnableAutoConfiguration. А то получается мы сначала отключаем автоконфиг, а потом снова включаем её

2024-10-21 15:50 UTC, SharkB38 commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
Тогда логично

2024-10-21 18:50 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> -        Update update = getUpdateForTelegramBot(user.getUsername(), message);
В этом ПРе этого быть не должно

2024-10-21 18:50 UTC, mysosnovskaya commented
И здесь тоже конфликты нужно пофиксить)

2024-10-22 21:50 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener implements MessageListener {
ок, посмотрю

2024-10-23 18:12 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> -        Update update = getUpdateForTelegramBot(user.getUsername(), message);
убрал

2024-10-25 20:48 UTC, mysosnovskaya approved these changes
Удали импорт, если он лишний, и можешь оба ПРа смержить)

2024-10-25 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/notificationservice/dto/UserDto.java
> +import org.apache.catalina.User;
А этот импорт здесь зачем?)

2024-10-27 15:37 UTC, KarabbasBarabas commented on src/main/java/faang/school/notificationservice/dto/UserDto.java
> +import org.apache.catalina.User;
откуда-то попал случайно

2024-10-27 15:40 UTC, merged

2024-10-27 15:40 UTC, KarabbasBarabas commented
готово