Feature BJS-2 26218 Многозадачные запросы
CorporationX/notification_service pull request #324
Opened 2024-11-08 15:36 UTC by segaTk

Промежуточное фиксирование, ожидаем задачу по cashback & balance.

2024-11-08 16:10 UTC, Silencemess1ah requested changes
В кафке не силен, убрать лишние строки, добавить значения конфига

2024-11-08 16:10 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaConsumersConfiguration.java
> +    private final KafkaProperties kafkaProperties;
Если это бин его надо инжектить

2024-11-08 16:10 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaProperties.java
> +
2 лишних строки

2024-11-08 16:10 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaTopicConfiguration.java
> +
лишняя строка

2024-11-08 16:10 UTC, Silencemess1ah commented on src/main/resources/application.yaml
> +
KafkaProperties есть а где эти пропертис?

2024-11-08 16:10 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaProperties.java
> +@ConfigurationProperties(prefix = "spring.data.kafka")
ты их вот здесь выставил, а сами значения не добавил

2024-11-08 16:12 UTC, Silencemess1ah commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaConsumersConfiguration.java
> +    private final KafkaProperties kafkaProperties;
Мой косяк, конструктор есть, значит будет внедрен, ед вопрос что он почему то private не знаю будет ли оно работать

2024-11-11 18:58 UTC, segaTk commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaProperties.java
> +
Да, убрал

2024-11-11 18:59 UTC, segaTk commented on src/main/resources/application.yaml
> +
Вот добавляю

2024-11-11 19:28 UTC, segaTk commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaProperties.java
> +@ConfigurationProperties(prefix = "spring.data.kafka")
добавил

2024-11-12 12:26 UTC, segaTk commented on src/main/java/faang/school/notificationservice/config/kafka/KafkaConsumersConfiguration.java
> +    private final KafkaProperties kafkaProperties;
да работает вроде, но поменял

2025-12-11 06:53 UTC, closed without merging