BJS2-41859 - Отправка Email сообщений
CorporationX/notification_service pull request #340
Opened 2024-12-02 19:12 UTC by Shakhaev

completed the task of sending notifications to email

2024-12-02 20:10 UTC, aplavina approved these changes

2024-12-02 20:10 UTC, aplavina commented on src/main/resources/application.yaml
> +#РњРѕР¶РЅРѕ Р·Р°СЂРµРіРёСЃС‚СЂРёСЂРѕРІР°С‚СЊ Р°РєРєР°СѓРЅС‚ Р±РµР· РїСЂРёРІСЏР·РєРё РєР°СЂС‚С‹. Р‘СѓРґРµС‚ 2 РµРІСЂРѕ РЅР° РѕС‚РїСЂР°РІРєСѓ С‚РµСЃС‚РѕРІС‹С… SMS
Тут что-то странное)

2024-12-03 05:54 UTC, Shakhaev commented on src/main/resources/application.yaml
> +#РњРѕР¶РЅРѕ Р·Р°СЂРµРіРёСЃС‚СЂРёСЂРѕРІР°С‚СЊ Р°РєРєР°СѓРЅС‚ Р±РµР· РїСЂРёРІСЏР·РєРё РєР°СЂС‚С‹. Р‘СѓРґРµС‚ 2 РµРІСЂРѕ РЅР° РѕС‚РїСЂР°РІРєСѓ С‚РµСЃС‚РѕРІС‹С… SMS
@aplavina Да, я тут крутил-мутил настройки. У меня локально сбились кодировки, и теперь кириллица отображается только так, к сожалению.

2024-12-06 16:54 UTC, MiraGlaceon requested changes

2024-12-06 16:54 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/service/EmailService.java
> +        message.setSubject("subject");
Subject - это тема сообщения? Тогда нужно сконструировать тему. Хотя бы от кого отправляется, айдишник юзера для этого есть

2024-12-07 09:59 UTC, Shakhaev commented on src/main/java/faang/school/notificationservice/service/EmailService.java
> +        message.setSubject("subject");
@MiraGlaceon внес изменения. Тут, скорее всего, лучше написать "Кому", поскольку уведомление автоматически формируется на стороне приложения. Решил сформировать как "For: " + user.getUsername().

2024-12-10 19:54 UTC, MiraGlaceon approved these changes

2024-12-10 21:18 UTC, merged