BJS2-41853 Отправка сообщений в Telegram
CorporationX/notification_service pull request #387
Opened 2024-12-09 17:27 UTC by waylaytessX

2024-12-11 18:02 UTC, bozhedar commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramBot.java
> +    }
На сколько я понял этот метод отвечает за то что бы бот оправил то же сообщение, что получил от пользователя. Наверно он тут лишний

2024-12-15 13:51 UTC, MiraGlaceon requested changes

2024-12-15 13:51 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/config/telegram/TelegramBotConfig.java
> +    public void createBot() {
Почему через постКонстракт, а не через бин?

2024-12-15 13:51 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramBot.java
> +            long chat_id = update.getMessage().getChatId();
Исключай такие константы chat_id. В java только методом camelCase именуем

2024-12-15 13:51 UTC, MiraGlaceon commented on src/main/resources/application.yaml
> +  telegram-bot:
Подобные вещи типа токенов скрывать бы из конфигов, чтобы доступы не светить в интернете. Нужно предусмотреть штатный механизм отказа, когда невозможно подключиться к телеграмм боту. Подобные конфиги скрыть, добавив в git игнор, а команду осведомить и можно им кинуть токены

2024-12-23 16:24 UTC, MiraGlaceon requested changes

2024-12-23 16:24 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +                .filter(service -> service.getPreferredContact() == user.getPreference())
Грубая ошибка сверять объекты оператором равенства, таким образом ты сверяешь ссылки, а не объекты. Попробуй переопределить equals в PreferredContact. Отпиши, почему решил заменить на оператор? У тебя до этого правильно было

2024-12-25 13:50 UTC, MiraGlaceon approved these changes

2024-12-25 14:26 UTC, merged