BJS2-41857 Уведомление о просмотре профиля
CorporationX/notification_service pull request #396
Opened 2024-12-12 13:18 UTC by waylaytessX

2024-12-13 11:15 UTC, Shakhaev commented on src/main/resources/messages.properties
> +profile_view.new = "Your profile has been viewed by a user {0} at {1}"
Привет! Классно, что ты выстраиваешь опциональное сообщение. Можно попробовать помещать вместо ID на позицию {0} - никнейм пользователя, который просмотрел профиль. По сути, если получить нотификацию, где указан просто ID человека, то это будет не очень информативно. Можно через UserServiceClient дергать дтошку из User Service, и из этой DTO вставлять уже никнейм.

2024-12-14 17:43 UTC, waylaytessX commented on src/main/resources/messages.properties
> +profile_view.new = "Your profile has been viewed by a user {0} at {1}"
Добавил, чтобы отображалось имя, благодарю!

2024-12-23 16:46 UTC, MiraGlaceon requested changes

2024-12-23 16:46 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +    MessageListenerAdapter profileViewListener(ProfileViewEventListener profileViewEventListener) {
Пропустил модификаторы доступа. Код стайл из-за этого хромает

2024-12-23 16:46 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +                .filter(service -> service.getPreferredContact() == user.getPreference())
Под одной из твоих задач уже задавал вопрос, жду ответ от тебя. Ты тут получаешь нужный сервис, давай попробуем изменить подход. Опиши, пожалуйста, логику что здесь происходит. Если тебе нужно получить нужный сервис оповещения по предпочтению пользователя, то можно ввести для этого enum и по enum получать нужный бин. Почитай как в spring из контейнера получать нужные бины. Либо есть ключевое слово instanceof, по этому слову можно определить нужный класс

2024-12-23 16:47 UTC, MiraGlaceon commented
Изучи вопрос по сравнению и определению бинов. Вопрос интересный, если не получится решить, то давай сядем на ПП, попробуем покопать

2024-12-23 16:58 UTC, waylaytessX commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +                .filter(service -> service.getPreferredContact() == user.getPreference())
Доброго вечера, не совсем понял суть вопроса. Проблема в некорректном сравнении enum, или в фильтрации сервисов?

2025-12-11 06:56 UTC, closed without merging