Feature bjs2 41899
CorporationX/notification_service pull request #397
Opened 2024-12-12 22:52 UTC by Alexey-Zimin

Интегрировать notification_service с Google SMTP для отправки нотификаций пользователю на его email.

Используем туториал: [Guide to Spring Email | Baeldung](https://www.baeldung.com/spring-email)  .

Нужно:

Полностью подключить либу;

Написать конфигурацию;

Сделать себе API key для Google SMTP на личном аккаунте.

Затем нужно создать EmailService — это будет класс, реализующий интерфейс NotificationService, который уже предоставлен. По сути, EmailService, получив параметры в метод интерфейса, должен отправить переданное сообщение на email переданного пользователя, используя Google SMTP.

Для проверки отправки сообщений сделал TestController, который дергал из постмана. Его в дальнейшем уберу из проекта.
![sendmail_postman](https://github.com/user-attachments/assets/45a4b886-59fa-43b0-8a53-fe2e0b52e49a)
![email](https://github.com/user-attachments/assets/fe6b7b11-14ee-4437-aefb-80e492b84353)
Свои данные на отправку почтовых сообщений из yml-файла убрал. Для того чтобы отпралять сообщения в дальнейшем необходимо будет создать корпоративный ящик. Для тестов можно свой указывать, предварительно необходимо сделать API key.

2024-12-16 10:29 UTC, RuslanGabd commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            String massage = String.format(NOT_THE_PREFERRED_PLATFORM, user.getId());
massage? опечатка?

2024-12-16 10:29 UTC, RuslanGabd commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        message.setTo(user.getEmail());
я бы заменил на message.setTo(user.getEmail().trim()); что бы избежать возможных пробелов

2024-12-16 10:29 UTC, RuslanGabd commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
лучше заменить на EmailValidator из Apache Commons Validator

2024-12-16 20:16 UTC, jibulani requested changes
хорошо

есть комменты от меня и от Руслана, надо поправить

2024-12-16 20:16 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/email/EmailConfig.java
> +    @Value("${mail.host}")
можно было бы вынести параметры в отдельный класс, помеченный как `@ConfigurationProperties(prefix="mail")`

некритично, но лучше знать про такое, обычно так делают
https://www.baeldung.com/configuration-properties-in-spring-boot

2024-12-16 20:16 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/email/EmailConfig.java
> +        properties.put("mail.debug", "true"); // ???????
тоже можно брать из параметров значение, чтобы для тестового окружения оно было true, а для прода false

2024-12-16 20:16 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/TestController.java
> +public class TestController {
для прода этот конструктор же не нужен
либо удалить, либо пометить, что инжектить только для тестового окружения через `@Profile("test")`, например
https://docs.spring.io/spring-boot/reference/features/profiles.html

2024-12-16 20:16 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +            Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
плюсую, лучше брать уже готовые реализации

2024-12-16 20:16 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/email/EmailService.java
> +        if (!user.getPreference().equals(UserDto.PreferredContact.EMAIL)) {
на мой взгляд избыточная проверка, может быть ситуация, когда у нас нет возможности через другие сервисы отправить нотификацию, тогда придется через емэйл отправлять

2024-12-16 20:16 UTC, jibulani commented on src/test/java/faang/school/notificationservice/service/email/EmailServiceTest.java
> +@ExtendWith(MockitoExtension.class)
хорошие тесты, молодец!

2024-12-18 20:50 UTC, jibulani approved these changes
супер!

2024-12-18 20:50 UTC, merged