BJS2-41767
CorporationX/notification_service pull request #403
Opened 2024-12-14 18:41 UTC by davidx5x5

2024-12-16 20:25 UTC, jibulani requested changes
хорошо!

есть пара небольших комментариев

2024-12-16 20:25 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/context/BotConfig.java
> +public class BotConfig {
обычно такие штуки делаются с помощью класса, помеченного аннотацией `@ConfigurationProperties(prefix="telegram.bot")`
https://www.baeldung.com/configuration-properties-in-spring-boot

2024-12-16 20:25 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/context/BotInitializer.java
> +    @EventListener({ContextRefreshedEvent.class})
зачем так?
можно проще с помощью аннотации `@PostConstruct`

2024-12-16 20:25 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> +        return UserDto.PreferredContact.valueOf("TELEGRAM");
надежнее так
`UserDto.PreferredContact.TELEGRAM`

2024-12-16 20:37 UTC, davidx5x5 commented on src/main/java/faang/school/notificationservice/config/context/BotConfig.java
> +public class BotConfig {
ок, да, так красивее, переделал, спасибо:)

2024-12-16 20:43 UTC, davidx5x5 commented on src/main/java/faang/school/notificationservice/config/context/BotInitializer.java
> +    @EventListener({ContextRefreshedEvent.class})
если поменять на @PostConstruct то ContextRefreshedEvent.class подчеркивает красным и пишет Cannot find method 'value

2024-12-16 20:44 UTC, davidx5x5 commented on src/main/java/faang/school/notificationservice/service/telegram/TelegramService.java
> +        return UserDto.PreferredContact.valueOf("TELEGRAM");
Ок, класс, мне тоже мой вариант не нравился, переделал, спасибо

2024-12-17 11:41 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/context/BotInitializer.java
> +    @EventListener({ContextRefreshedEvent.class})
а там будет просто PostConstruct без аргументов

2024-12-17 11:42 UTC, jibulani approved these changes
супер!

2024-12-17 11:42 UTC, merged