Feature/BJS2 41855 - Уведомление о принятии запроса на менторство
CorporationX/notification_service pull request #405
Opened 2024-12-15 08:51 UTC by frs717

2024-12-15 14:22 UTC, bozhedar approved these changes

2024-12-17 13:49 UTC, Shakhaev approved these changes

2024-12-23 16:32 UTC, MiraGlaceon requested changes

2024-12-23 16:32 UTC, MiraGlaceon commented on src/main/java/faang/school/notificationservice/NotificationServiceApp.java
>      public ObjectMapper objectMapper() {
Не твои действия, но подправить нужно. Вынеси ObjectMapper в отдельный пакет. Он тебе для редиса нужен, туда в конфиги перенести можно

2024-12-29 15:26 UTC, frs717 commented on src/main/java/faang/school/notificationservice/NotificationServiceApp.java
>      public ObjectMapper objectMapper() {
Исправлено

2025-01-10 03:42 UTC, MiraGlaceon approved these changes

2025-12-11 06:56 UTC, closed without merging