BJS2-41896-notification-service
CorporationX/notification_service pull request #411
Opened 2024-12-19 11:44 UTC by RuslanGabd

2024-12-19 11:54 UTC, RuslanGabd commented
![image](https://github.com/user-attachments/assets/2dc7a73b-5913-411c-8d06-860575247e3b)

2024-12-19 16:18 UTC, jibulani requested changes
есть вопросы + не хватает тестов

2024-12-19 16:18 UTC, jibulani commented on src/main/java/faang/school/notificationservice/messaging/MentorshipOfferedMessageBuilder.java
> +    private String getMessageTemplate(Locale locale) {
почему не через MessageSource и messages.properties сделал?

2024-12-19 16:18 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/EventService.java
> +        // emailService.send(userDto, message);
недоделано?

2024-12-19 16:18 UTC, jibulani commented on src/main/java/faang/school/notificationservice/messaging/NotificationChannel.java
> +public interface NotificationChannel {
зачем?

2024-12-19 16:18 UTC, jibulani commented on src/main/java/faang/school/notificationservice/model/ContactPreference.java
> +public class ContactPreference {
для чего нужен?

2024-12-19 16:18 UTC, jibulani commented on src/main/resources/application.yaml
> +        mentorshipOfferedChannel:
почему не сделал по аналогии с follower и achievement?

2024-12-20 07:36 UTC, RuslanGabd commented on src/main/resources/application.yaml
> +        mentorshipOfferedChannel:
потому что ошибка если по аналогии делать:
![image](https://github.com/user-attachments/assets/b758f761-0819-4f92-9717-c6dfbd7c34a4)

2024-12-20 21:16 UTC, jibulani commented on src/main/resources/application.yaml
> +        mentorshipOfferedChannel:
трудно по скрину понять, лучше полный текст ошибки присылать

2024-12-20 21:52 UTC, jibulani requested changes
в целом хорошо, но есть необходимость рефакторинга и исправлений

2024-12-20 21:52 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/EventService.java
этот класс выглядит, как NotificationSender, в который из разных листенеров приходят запросы на отправку сообщений пользователю по id, то есть сюда уже должны приходить сформированные сообщения и id пользователя

этот сервис должен через UserServiceClient  получить инфу о юзере и подобрать нужную реализацию NotificationService на основании предпочтения пользователя по способу нотификации
для подбора сервиса нотификации нужно действовать по аналогии с фильтрами в 5-6 спринтах - заинжектить List<NotificationService> и на основании метода getPreferredContact выбрать нужный, после чего отправить через него сообщение. А при твоем подходе, если у нас появится новая реализация NotificationService, нужно будет не забыть прописать его тут и еще добавить в switch-case.

видимо, при первом ревью не обратил внимание, сори

2024-12-20 21:52 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/EventService.java
> +        String message = builder.buildMessage(new MentorshipOfferedEvent(idRequest, idAuthor, idReceiver), Locale.ENGLISH);
я бы вынес локаль в конфиг, чтобы при  ее изменении достаточно было поправить значение в application.properties, а не менять по всему проекту

2024-12-20 21:52 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/EventService.java
> +        return new UserDto();
почему так? забыл доделать?

2024-12-20 21:52 UTC, jibulani commented on src/main/resources/messages.properties
> +follower.new = "Congrats! You've got a new follower!"
для проверки работы можно с разными локалями messages.properties добавить, некритично

2024-12-20 21:52 UTC, jibulani commented on src/test/java/faang/school/notificationservice/service/EventServiceTest.java
> +class EventServiceTest {
хорошие тесты, молодец!

2024-12-21 21:24 UTC, jibulani approved these changes
хорошо, молодец!

2024-12-22 05:32 UTC, merged