SmsService
CorporationX/notification_service pull request #415
Opened 2024-12-20 05:28 UTC by Amanyaz

Была создана конфигурационная класс Vonage и класс SmsService для отправки SMS через Vonage. Были внесены необходимые изменения в файл application.yaml. Разработаны модульные тесты. Для проверки корректной работы SmsService и отправки SMS я создал временный контроллер и протестировал с помощью Postman. SMS было успешно отправлено.

2024-12-20 10:01 UTC, alexFromAC143937 reviewed
Супер. Было интересно посмотреть.

2024-12-20 10:01 UTC, alexFromAC143937 commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +        log.info("Sending SMS to: {}", user.getPhone());
Не критично: долго думал о логировании, пришел к заключению, что логирование стоит делать первой строкой, тогда если упадет, будет четко видно + передавать одной строкой, если передавать 2-мя строками, то будет вариант, когда  будет 10000ХХХ пользователей, строки будут перемешаны.

2024-12-21 00:29 UTC, Amanyaz commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +        log.info("Sending SMS to: {}", user.getPhone());
Сделано!

2024-12-21 00:37 UTC, alexFromAC143937 approved these changes

2024-12-21 21:17 UTC, jibulani requested changes
хорошо, молодец!

есть небольшие комментарии

2024-12-21 21:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +        log.info("Message: {}", message);
не понял, зачем на два лога разбивать это сообщение и предыдущее
еще вижу, что довольно много info-логов, так на реальном проекте лучше не делать - забьете все место на сервере бесполезными логами и админы будут на вас ругаться

для логгирования стандартного поведения лучше использовать log.debug - этот уровень логгирования по умолчанию выключен и такие логи не будут сохраняться и занимать место, а если что-то сломается, то можно ненадолго включить сохранение debug-логов для выяснения причин проблемы

2024-12-21 21:17 UTC, jibulani commented on src/main/resources/application.yaml
> +    secret: t6qqwTma9etW5JwR
лучше не хранить такие данные в коде, для хранения паролей используются специальные инструменты, например, vault
в рамках проекта мы эти инструменты не можем охватить, это больше по части администрирования, поэтому оставь просто старые значения, если кому потребуется протестить смс - спросит у тебя, что сюда ввести

2024-12-21 21:17 UTC, jibulani commented on src/test/java/faang/school/notificationservice/service/sms/SmsServiceTest.java
> +    public void sendUnsuccessfulTest() {
чем отличается от предыдущего теста?

2024-12-21 21:17 UTC, jibulani commented on src/test/java/faang/school/notificationservice/service/sms/SmsServiceTest.java
> +        verify(smsClient, times(1)).submitMessage(sms);
times(1) можно на only() заменить

2024-12-22 03:34 UTC, Amanyaz commented on src/main/java/faang/school/notificationservice/service/sms/SmsService.java
> +        log.info("Message: {}", message);
Вроде сделал!

2024-12-22 03:34 UTC, Amanyaz commented on src/main/resources/application.yaml
> +    secret: t6qqwTma9etW5JwR
Сделано!

2024-12-22 03:34 UTC, Amanyaz commented on src/test/java/faang/school/notificationservice/service/sms/SmsServiceTest.java
> +        verify(smsClient, times(1)).submitMessage(sms);
Сделано!

2024-12-22 03:34 UTC, Amanyaz commented on src/test/java/faang/school/notificationservice/service/sms/SmsServiceTest.java
> +    public void sendUnsuccessfulTest() {
Вроде сделал!

2024-12-22 21:29 UTC, jibulani approved these changes
отлично!

2024-12-22 21:29 UTC, merged