BJS2-41753 add Listener Recommendation
CorporationX/notification_service pull request #417
Opened 2024-12-21 10:58 UTC by AlexLogino

2024-12-23 20:04 UTC, evgen-backend-rostov commented on src/main/java/faang/school/notificationservice/listeners/AbstractEventListener.java
> +    protected T getEvent(Message message, Class<T> clazz) {
для читабельности переменную можно назвать eventType или просто type, хотя clazz звучит прикольнее)

2024-12-23 20:09 UTC, evgen-backend-rostov commented on src/main/java/faang/school/notificationservice/dto/publisher_events/RecommendationReceivedEvent.java
> +package faang.school.notificationservice.dto.publisher_events;
по идее, папку можно просто назвать events, и не разделять события на publisher и listener. Просто ещё по правилу именовая папок их вроде не принято через "_" разделять

2024-12-23 20:12 UTC, evgen-backend-rostov commented
По логике работы мне всё понятно, оставил парочку орфографических комментов

2024-12-24 17:06 UTC, AlexLogino commented on src/main/java/faang/school/notificationservice/listeners/AbstractEventListener.java
> +    protected T getEvent(Message message, Class<T> clazz) {
clazz вроде тоже часто пишут

2024-12-24 17:13 UTC, AlexLogino commented on src/main/java/faang/school/notificationservice/dto/publisher_events/RecommendationReceivedEvent.java
> +package faang.school.notificationservice.dto.publisher_events;
разве не принято? вроде как раз snake_case и используется для именования папок

касаемо непосредственно названия, то в listener все лисенеры будут лежать, а ивенты это дтошки же, поэтому в папке дто... ну могу просто events обозвать

2024-12-26 17:02 UTC, jibulani requested changes
все хорошо, есть пара небольших комментариев

2024-12-26 17:02 UTC, jibulani commented on src/test/java/faang/school/notificationservice/messaging/RecommendationReceivedMessageBuilderTest.java
> +        Assertions.assertEquals(result, "User {0} given recommendation for You");
почему "User {0} given recommendation for You" а не "User Alex given recommendation for You" ?

2024-12-26 17:02 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/RedisConfig.java
> +    @Bean
зачем как бин помечен?

2024-12-28 18:12 UTC, AlexLogino commented on src/test/java/faang/school/notificationservice/messaging/RecommendationReceivedMessageBuilderTest.java
> +        Assertions.assertEquals(result, "User {0} given recommendation for You");
просто "Alex" добавил сильно позже, чем шаблон и забыл сменить здесь

2024-12-28 18:15 UTC, AlexLogino commented on src/main/java/faang/school/notificationservice/config/RedisConfig.java
> +    @Bean
всё бином помечено) подумал, что это тоже надо

2024-12-29 12:28 UTC, jibulani approved these changes
хорошо!

2024-12-29 12:29 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/RedisConfig.java
> +    @Bean
рекомендую на каникулах пересмотреть материалы по конфигурации спринга, чтобы больше понимания было :)

2024-12-29 12:29 UTC, merged