Feature bjs2 41900
CorporationX/notification_service pull request #418
Opened 2024-12-21 16:29 UTC by Alexey-Zimin

Задание
Когда achievement_service выдает любому пользователю любое достижение, то это ведь большое событие в системе! Вероятно, другие сервисы захотят о нём узнать. Например, notification_service мог бы быть заинтересован в таком событии и отправить получателю достижения нотификацию об этом.

Поэтому achievement_service должен уметь публиковать в Redis топик событие каждый раз, когда выдает кому-либо любое достижение. Для этого нужно создать необходимую Spring-конфигурацию и сделать специальный компонент AchievementPublisher, который и будет заниматься публикацией события о достижении пользователя.

В сервисе реализован функционал, который отправляет через redis сообщения. Фуекционал, который принимает сообщения реализован в сервисе notification_service. Его смотреть нужно здесь:

Для тестирования сделал TestController.
![redis_postman](https://github.com/user-attachments/assets/f6c68271-4ae2-43c3-b231-58c7ccb3b176)
![redis_mail](https://github.com/user-attachments/assets/b49d98a3-b36c-4ea4-b805-bfa7aa5be358)

2024-12-21 23:30 UTC, alexFromAC143937 approved these changes

2024-12-23 20:17 UTC, jibulani requested changes
нужно ребейзнуться и переиспользовать то, что уже есть в мастере

2024-12-23 20:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/redis/RedisConfig.java
> +public class RedisConfig {
для этих целей есть же уже RedisConfiguration, почему там не сделал доработку?

2024-12-23 20:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +public abstract class AbstractEventListener<T> {
в мастере уже есть

2024-12-23 20:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/listener/AbstractEventListener.java
> +    protected void sendNotification(Long id, String message) {
есть в мастере в NotificationSender

2024-12-23 20:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/messaging/MessageBuilder.java
> +//    boolean supportsEventType(T eventType);
забыл удалить?

2024-12-23 20:17 UTC, jibulani commented on src/main/java/faang/school/notificationservice/validator/UserValidator.java
> +public class UserValidator {
есть в мастере внутри NotificationSender

2024-12-24 16:49 UTC, jibulani requested changes
хорошо, пару небольших правок осталось сделать

2024-12-24 16:49 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/reddis/RedisConfiguration.java
> +    ChannelTopic mentorshipOfferedTopic() {
модификатор public пропал

2024-12-24 16:49 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/reddis/RedisConfiguration.java
> +    MessageListenerAdapter mentorshipOfferedListener(MentorshipOfferedEventListener mentorshipOfferedEventListener) {
и тут

2024-12-24 16:49 UTC, jibulani commented on src/main/java/faang/school/notificationservice/config/reddis/RedisConfiguration.java
>  package faang.school.notificationservice.config.reddis;
поправь название пакета на redis, пожалуйста
не заметил опечатку в предыдущем pr

2024-12-24 17:24 UTC, jibulani approved these changes
супер!

2024-12-24 17:25 UTC, merged