add listener
CorporationX/notification_service pull request #64
Opened 2023-09-07 10:17 UTC by TowBoat39

2023-09-07 16:58 UTC, M437A approved these changes

2023-09-08 09:26 UTC, InnMish requested changes

2023-09-08 09:26 UTC, InnMish commented on src/main/java/faang/school/notificationservice/config/RedisConfig.java
> +    }
Давай то же самое еще для второго бина сделаем, который не твой 
Чтобы у нас единая логика тут была 
Чтобы бины в контейнере не конфликтовали, навесь Qualifier на них потом

2023-09-08 09:26 UTC, InnMish commented on src/main/java/faang/school/notificationservice/message/RecommendationRequestMessageBuilder.java
> +        return messageSource.getMessage("recommendation_request.new", new Object[]{}, locale);
а что у нас будет лежать в new Object? Какое в итоге сообщение получит пользователь? Может туда добавить какие-то данные из эвента?

2023-09-08 09:26 UTC, InnMish commented on src/main/resources/messages_en.properties
> +recommendation_request.new="You got a new recommendation request"
Тут тоже можно подумать в сторону переноса в ямл файл, как в другой фиче писала

2023-09-12 13:25 UTC, InnMish requested changes

2023-09-12 13:25 UTC, InnMish commented on src/main/java/faang/school/notificationservice/config/RedisConfig.java
> +    public RedisMessageListenerContainer redisContainer(MessageListenerAdapter skillOfferListenerAdapter, MessageListenerAdapter recommendationRequestListenerAdapter) {
Qualifier

2023-09-13 15:19 UTC, merged